### ISSUE TITLE
Consider switching to controllers

### ISSUE THREAD

**Issue by smallketchup82** [Galaxypedia-Wiki/GalaxyGPT#51]
idk if we should continue with the minimal api or use controllers

either way, the api feels as though it can break with a touch and i dont like it

**Comment by smallketchup82** [comment]
@CornHusker89 need your thoughts on this

**Comment by CornHusker89** [comment]
i dont think its worth the time for now. api does have some interesting things we can do with it too like making the api public or something

**Comment by smallketchup82** [comment]
you're right, i shouldn't violate yagni. will keep this stale for now
