### ISSUE TITLE
Host datasets publicly

### ISSUE THREAD

**Issue by smallketchup82** [Galaxypedia-Wiki/GalaxyGPT#68]
can probably host them somewhere somehow

**Comment by smallketchup82** [comment]
v@CornHusker89 this too

**Comment by CornHusker89** [comment]
if a functioning form of galaxygpt is public then i think it's fine to keep it how it is, otherwise i think either a public api or this would be a good idea

**Comment by smallketchup82** [comment]
it's mostly that this thing is licensed under GPL, but nobody can really test it since they dont have a dataset.

i'll bite the bullet and host them publicly. i guess i'll just host them using github's cdn in the readme
